#!/bin/bash
# shell script for procesing last tweets

if [ $# -ne 3 ]
then
   echo "usage: make_last_tweets experiment root TZ"
      exit 1
fi


experiment=$1
store=${root}/store
scripts=${root}/scripts/
resources=${root}/resources/
TZ=$4


path=${name_file%/*}
file_in=${name_file##*/}
base=${file_in%%.*}
ext=${file_in#*.}

echo "... running last tweets"

for file in $(ls ${store}/*${experiment}_*.txt); do
  file_in=${file##*/}
  base=${file_in%%.*}
  
  status_file=${base}_counter_status.txt
  echo "${store}/${file_in}" 
  if [ -e "${store}/${experiment}/filter.txt" ] || [ -e "${store}/${experiment}/select.txt" ]
    then
      echo "False positive filter"
      python2.7 ${scripts}tweets_select_filter.py ${file_in} --dir_in ${store}/ --filter_users ${store}/${experiment}/filter.txt --filter_names ${store}/${experiment}/filter.txt --select_users ${store}/${experiment}/select.txt --select_names ${store}/${experiment}/select.txt
      file_in=${base}.sel
  fi
  echo " running package counters ${store}/ ${file_in}  "
  python2.7 ${scripts}tweets_counter.py ${file_in} --filter ${store}/languages/filter.all  --dir_in ${store}/ --dir_out ${store}/${experiment}/ --TZ ${TZ}
  echo " running package talk ${store}/ ${file_in}  "
  python2.7 ${scripts}tweets_talk.py ${file_in}   --dir_in ${store}/ --dir_out ${store}/${experiment}/ --TZ ${TZ}
  echo " running package location ${store}/ ${file_in}  "
  python2.7 ${scripts}tweets_location.py ${file_in} ${resources}/recursos_loc.txt --dir_in ${store}/ --dir_out ${store}/${experiment}/ --TZ ${TZ}
done 




