#!/bin/bash
# shell script for procesing last tweets

if [ $# -ne 3 ]
then
   echo "usage: make_last_tweets experiment store resources"
      exit 1
fi


experiment=$1
store=$2
resources=$3


path=${name_file%/*}
file_in=${name_file##*/}
base=${file_in%%.*}
ext=${file_in#*.}

echo "... running last tweets"

for file in $(ls ${store}/*${experiment}_*.txt); do
  file_in=${file##*/}
  base=${file_in%%.*}
  
  status_file=${base}_counter_status.txt
  echo "${store}/${file_in}" 
  if [ -e "${store}/datos_${experiment}/filter.txt" ]
    then
      echo "quito spam"
      $HOME/t-hoarder/tweets_select_filter.py ${file_in} --dir_in ${store}/ --filter_users ${store}/datos_${experiment}/filter.txt --filter_names ${store}/datos_${experiment}/filter.txt
      file_in=${base}.sel
  fi
  echo " running package counters ${store}/ ${file_in}  "
  $HOME/t-hoarder/tweets_counter.py ${file_in} --stopwords ${store}/languages/filter.all  --dir_in ${store}/ --dir_out ${store}/datos_${experiment}/
  echo " running package talk ${store}/ ${file_in}  "
  $HOME/t-hoarder/tweets_talk.py ${file_in}   --dir_in ${store}/ --dir_out ${store}/datos_${experiment}/
  echo " running package location ${store}/ ${file_in}  "
  $HOME/t-hoarder/tweets_location.py ${file_in} ${resources}/recursos_loc.txt --dir_in ${store}/ --dir_out ${store}/datos_${experiment}/
done 




