#!/bin/bash
# shell script for procesing blocks

if [ $# -ne 4 ]
then
   echo "usage: make_blocks experiment store resources"
      exit 1
fi


experiment=$1
store=$2
resources=$3
tz=$4

path=${name_file%/*}
file_in=${name_file##*/}
base=${file_in%%.*}
ext=${file_in#*.}


echo "... running packages"

for file in $(ls ${store}/*${experiment}*.tar.gz); do
  file_in=${file##*/}
  base=${file_in%%.*}
  status_file=${base}_counter_status.txt
  
  echo "file status ${store}/datos_${experiment}/${status_file}/"
  if [ -e ${store}/datos_${experiment}/${status_file} ]
  then 
    echo " Package counters done ${store}/${file_in}  "
  else
    if [ -e "${store}/datos_${experiment}/filter.txt" ] || [ -e "${store}/datos_${experiment}/select.txt" ]
    then
      echo "False positive filter"
      $HOME/t-hoarder/tweets_select_filter.py ${file_in} --dir_in ${store}/ --filter_users ${store}/datos_${experiment}/filter.txt --filter_names ${store}/datos_${experiment}/filter.txt --select_users ${store}/datos_${experiment}/select.txt --select_names ${store}/datos_${experiment}/select.txt
      file_in=${base}.sel.gz
    fi

    echo " running package counters ${store}/ ${file_in}  "
    $HOME/t-hoarder/tweets_counter.py ${file_in} --filter ${store}/languages/filter.all  --dir_in ${store}/ --dir_out ${store}/datos_${experiment}/ --TZ ${tz}
  fi 
  status_file=${base}_talk_status.txt
  if [ -e ${store}/datos_${experiment}/${status_file} ]
  then 
    echo " Package talk done ${store}/${file_in}  "
  else
    echo " running package talk ${store}/ ${file_in}  "
    $HOME/t-hoarder/tweets_talk.py ${file_in}   --dir_in ${store}/ --dir_out ${store}/datos_${experiment}/ --TZ ${tz}
  fi 
  status_file=${base}_loc_status.txt
  if [ -e ${store}/datos_${experiment}/${status_file} ]
  then 
    echo " Package location done ${store}/${file_in}  "
  else
    echo " running package location ${store}/ ${file_in}  "
    $HOME/t-hoarder/tweets_location.py ${file_in} ${resources}/recursos_loc.txt --dir_in ${store}/ --dir_out ${store}/datos_${experiment}/
  fi 
done 
