#!/bin/bash
# shell script for procesing blocks

if [ $# -ne 3 ]
then
   echo "usage: make_blocks experiment root"
      exit 1
fi


experiment=$1
root=$2
store=${root}/store/
scripts=${root}/scripts/
resources=${root}/resources/
tz=$4

path=${name_file%/*}
file_in=${name_file##*/}
base=${file_in%%.*}
ext=${file_in#*.}


echo "... running packages"

for file in $(ls ${store}/*${experiment}*.tar.gz); do
  file_in=${file##*/}
  base=${file_in%%.*}
  status_file=${base}_counter_status.txt
  
  echo "file status ${store}/${experiment}/${status_file}/"
  if [ -e ${store}/${experiment}/${status_file} ]
  then 
    echo " Package counters done ${store}/${file_in}  "
  else
    if [ -e "${store}/${experiment}/filter.txt" ] || [ -e "${store}/${experiment}/select.txt" ]
    then
      echo "False positive filter"
      python2.7 ${scripts}tweets_select_filter.py ${file_in} --dir_in ${store}/ --filter_users ${store}/${experiment}/filter.txt --filter_names ${store}/${experiment}/filter.txt --select_users ${store}/${experiment}/select.txt --select_names ${store}/${experiment}/select.txt
      file_in=${base}.sel.gz
    fi

    echo " running package counters ${store}/ ${file_in}  "
    python2.7 ${scripts}tweets_counter.py ${file_in} --filter ${store}/languages/filter.all  --dir_in ${store}/ --dir_out ${store}/${experiment}/ --TZ ${tz}
  fi 
  status_file=${base}_talk_status.txt
  if [ -e ${store}/${experiment}/${status_file} ]
  then 
    echo " Package talk done ${store}/${file_in}  "
  else
    echo " running package talk ${store}/ ${file_in}  "
    python2.7 ${scripts}tweets_talk.py ${file_in}   --dir_in ${store}/ --dir_out ${store}/${experiment}/ --TZ ${tz}
  fi 
  status_file=${base}_loc_status.txt
  if [ -e ${store}/${experiment}/${status_file} ]
  then 
    echo " Package location done ${store}/${file_in}  "
  else
    echo " running package location ${store}/ ${file_in}  "
    python2.7 ${scripts}tweets_location.py ${file_in} ${resources}/recursos_loc.txt --dir_in ${store}/ --dir_out ${store}/${experiment}/
  fi 
done 
