#!/bin/bash
# shell script for install t-hoarder
if [ ! -d ../t-hoarder ]
  then
    echo " t-hoarder directory doesn't exist"
    exit
fi
mkdir store
mkdir keys
mkdir web
dir_scripts=`pwd`/scripts
echo ${dir_scripts}
echo "export PATH=${dir_scripts}:$PATH" >> $HOME/.bashrc
export PATH=${dir_scripts}:$PATH
echo "enviroment created"
